#pragma once

enum OBJID			{ OBJ_MONEFFECT, OBJ_MONSTER, OBJ_EFFECT, OBJ_PLAYER, OBJ_SWORD, OBJ_SPIKE, OBJ_UI, OBJ_RECTANGLE, OBJ_BUTTON, OBJ_END };

enum DIRID			{ };

enum LINEID			{ LEFT, RIGHT, LINE_END };

enum OBJECT_STATE	{ AIR, WALL, GROUND };

enum OBJECT_LOOK	{ LOOK_LEFT, LOOK_RIGHT, LOOK_END };

enum SCENEID		{ SC_LOGO, SC_MENU, SC_EDIT, SC_START_STAGE, SC_FIRST_STAGE, SC_MANTIS_LORDS_STAGE, SC_THE_RADIANCE_STAGE, SC_END };

enum UNTOUCHABLE	{ OFF, ON };

enum IDENTIFY		{ LEFT_LORD, MIDDLE_LORD, RIGHT_LORD };

enum HP_STATE		{ HP_IDLE, HP_FILL, HP_BREAK };

enum SOUL_STATE		{ SOUL_0, SOUL_10, SOUL_20, SOUL_30, SOUL_40, SOUL_50, SOUL_60, SOUL_70, SOUL_80, SOUL_90 };

enum CHANNELID		{ SOUND_EFFECT, SOUND_BGM, SOUND_PLAYER, SOUND_MANTIS_LORD, SOUND_THE_RADIANCE, MAXCHANNEL };